name: generator
on:
  pull_request:
    branches:
      - 'main'
  push:
  workflow_dispatch:

# Default values to simplify job configurations below.
env:
  GO_VERSION: '1.19'
  PY_VERSION: '3.11'

jobs:
  generation:
    runs-on: ubuntu-latest
    name: ${{ matrix.app }}-${{ matrix.lang }}
    strategy:
      fail-fast: false
      matrix:
        lang:
          - go
          - py
        app:
          - sonarr
          - radarr
          - lidarr
          - readarr
          - whisparr
          - prowlarr
          - overseerr
        include:
          - app: sonarr
            swagger: https://raw.githubusercontent.com/Sonarr/Sonarr/076aaba9083900cb6c9cd01459d0e016c66e31d2/src/Sonarr.Api.V3/openapi.json
          - app: radarr
            swagger: https://raw.githubusercontent.com/Radarr/Radarr/e5d479a162b5159bfc38aa6a32f40d89b433f9c8/src/Radarr.Api.V3/openapi.json
          - app: lidarr
            swagger: https://raw.githubusercontent.com/Lidarr/Lidarr/f35173e670fa33a68f05ae1d8d3f63bc427e51fd/src/Lidarr.Api.V1/openapi.json
          - app: readarr
            swagger: https://raw.githubusercontent.com/Readarr/Readarr/bd25c9e3e0e94a19b9e490f46c354fe219486910/src/Readarr.Api.V1/openapi.json
          - app: whisparr
            # swagger: https://raw.githubusercontent.com/Whisparr/Whisparr/faa43c8c73727156665173629d54355ecbf017d8/src/Whisparr.Api.V3/openapi.json
            swagger: https://raw.githubusercontent.com/Radarr/Radarr/e5d479a162b5159bfc38aa6a32f40d89b433f9c8/src/Radarr.Api.V3/openapi.json
          - app: prowlarr
            swagger: https://raw.githubusercontent.com/Prowlarr/Prowlarr/b37d8799a0a4e79fd3249955760e4f6b0ac8f179/src/Prowlarr.Api.V1/openapi.json
          - app: overseerr
            swagger: https://raw.githubusercontent.com/sct/overseerr/3ea5076053359b518b1b4d537e7b61580d9275a3/overseerr-api.yml

    steps:
      - name: DevOpsArrBOT token
        id: DevOpsArrBOT
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: '305652'
          private_key: ${{ secrets.DEVOPSARRBOT_PRIVATE_KEY }}

      - name: set DevOpsArrBOT config
        run: |
          git config --global user.name "devopsarr[bot]"
          git config --global user.email 127950054+devopsarr[bot]@users.noreply.github.com

      - name: Check out code
        uses: actions/checkout@v4

      - name: Checkout sdk
        uses: actions/checkout@v4
        with:
          repository: devopsarr/${{ matrix.app }}-${{ matrix.lang }}
          path: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
          fetch-depth: 0
          token: ${{ steps.DevOpsArrBOT.outputs.token }}

      # Needed for processing the swaggers
      - name: Set up yq
        uses: frenck/action-setup-yq@v1.0.2
        with:
          version: v4.34.2

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Set up Golang
        if: ${{ matrix.lang == 'go' }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Git Version
        run: |
          tag=$(git describe --tags --abbrev=0) &&\
          echo "version=${tag:1}" >> $GITHUB_OUTPUT
        id: version
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: generation
        run: |
          make generate
        env:
          APP: ${{ matrix.app }}
          SDK: ${{ matrix.lang }}
          URL: ${{ matrix.swagger }}
          VERSION: ${{ steps.version.outputs.version }}

      - name: diff
        id: diff
        run: |
          git diff --exit-code ||\
          echo "create-pr=true" >> $GITHUB_OUTPUT
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: create commit
        if: ${{ github.event_name == 'pull_request' && steps.diff.outputs.create-pr == 'true'}}
        run: |
          git checkout -b feature/code-generation &&\
          git add . &&\
          git commit -m "${{ github.event.pull_request.title }}" &&\
          git push --set-upstream origin feature/code-generation -f
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: create pull request
        if: ${{ steps.diff.outputs.create-pr == 'true' && github.event_name != 'push' }}
        run: gh pr create -H feature/code-generation -B main --title '${{ github.event.pull_request.title }}' --body 'Code generated' || echo 'PR already created'
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
        env:
          GITHUB_TOKEN: ${{ steps.DevOpsArrBOT.outputs.token }}

      - name: merge pull request
        if: ${{ steps.diff.outputs.create-pr == 'true' && github.event_name == 'push' && github.ref_name == 'main' }}
        run: gh pr merge feature/code-generation --merge
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
        env:
          GITHUB_TOKEN: ${{ steps.DevOpsArrBOT.outputs.token }}