name: generator
on:
  pull_request:
    branches:
      - 'main'
  push:
  workflow_dispatch:

# Default values to simplify job configurations below.
env:
  GO_VERSION: '1.19'
  PY_VERSION: '3.11'

jobs:
  generation:
    runs-on: ubuntu-latest
    name: ${{ matrix.app }}-${{ matrix.lang }}
    strategy:
      fail-fast: false
      matrix:
        lang:
          - go
          - py
        app:
          - sonarr
          - radarr
          - lidarr
          - readarr
          - whisparr
          - prowlarr
        include:
          - app: sonarr
            swagger: https://raw.githubusercontent.com/Sonarr/Sonarr/d606144e005141e070449034c6f719016f1d37a9/src/Sonarr.Api.V3/openapi.json
          - app: radarr
            swagger: https://raw.githubusercontent.com/Radarr/Radarr/a471f1b44f51fa245caae4bb853a3ef45e80e541/src/Radarr.Api.V3/openapi.json
          - app: lidarr
            swagger: https://raw.githubusercontent.com/Lidarr/Lidarr/7444bebe691116da5063ff74c0e354e648cc15f4/src/Lidarr.Api.V1/openapi.json
          - app: readarr
            swagger: https://raw.githubusercontent.com/Readarr/Readarr/43367504a413e19de310e46c87992cfe2a197d4d/src/Readarr.Api.V1/openapi.json
          - app: whisparr
            # swagger: https://raw.githubusercontent.com/Whisparr/Whisparr/eb79bb0a7fd78c5728b052c60f8b4e74dbc3d331/src/Whisparr.Api.V3/openapi.json
            swagger: https://raw.githubusercontent.com/Radarr/Radarr/a471f1b44f51fa245caae4bb853a3ef45e80e541/src/Radarr.Api.V3/openapi.json
          - app: prowlarr
            swagger: https://raw.githubusercontent.com/Prowlarr/Prowlarr/ea635e685b80d372856c056e48fb5faf7c4f6565/src/Prowlarr.Api.V1/openapi.json

    steps:
      - name: DevOpsArrBOT token
        id: DevOpsArrBOT
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: '305652'
          private_key: ${{ secrets.DEVOPSARRBOT_PRIVATE_KEY }}

      - name: set DevOpsArrBOT config
        run: |
          git config --global user.name "devopsarr[bot]"
          git config --global user.email 127950054+devopsarr[bot]@users.noreply.github.com

      - name: Check out code
        uses: actions/checkout@v3

      - name: Checkout sdk
        uses: actions/checkout@v3
        with:
          repository: devopsarr/${{ matrix.app }}-${{ matrix.lang }}
          path: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
          fetch-depth: 0
          token: ${{ steps.DevOpsArrBOT.outputs.token }}

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Set up Golang
        if: ${{ matrix.lang == 'go' }}
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Git Version
        run: |
          tag=$(git describe --tags --abbrev=0) &&\
          echo "version=${tag:1}" >> $GITHUB_OUTPUT
        id: version
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: generation
        run: |
          make generate
        env:
          APP: ${{ matrix.app }}
          SDK: ${{ matrix.lang }}
          URL: ${{ matrix.swagger }}
          VERSION: ${{ steps.version.outputs.version }}

      - name: diff
        id: diff
        run: |
          git diff --exit-code ||\
          echo "create-pr=true" >> $GITHUB_OUTPUT
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: create commit
        if: ${{ github.event_name == 'pull_request' && steps.diff.outputs.create-pr == 'true'}}
        run: |
          git checkout -b feature/code-generation &&\
          git add . &&\
          git commit -m "${{ github.event.pull_request.title }}" &&\
          git push --set-upstream origin feature/code-generation -f
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: create pull request
        if: ${{ steps.diff.outputs.create-pr == 'true' && github.event_name != 'push' }}
        run: gh pr create -H feature/code-generation -B main --title '${{ github.event.pull_request.title }}' --body 'Code generated' || echo 'PR already created'
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
        env:
          GITHUB_TOKEN: ${{ steps.DevOpsArrBOT.outputs.token }}
      
      - name: merge pull request
        if: ${{ steps.diff.outputs.create-pr == 'true' && github.event_name == 'push' && github.ref_name == 'main' }}
        run: gh pr merge feature/code-generation --merge
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
        env:
          GITHUB_TOKEN: ${{ steps.DevOpsArrBOT.outputs.token }}