name: generator
on:
  pull_request:
    branches:
      - 'main'
  push:
  workflow_dispatch:

# Default values to simplify job configurations below.
env:
  GO_VERSION: '1.19'
  PY_VERSION: '3.11'

jobs:
  generation:
    runs-on: ubuntu-latest
    name: ${{ matrix.app }}-${{ matrix.lang }}
    strategy:
      fail-fast: false
      matrix:
        lang:
          - go
          - py
        app:
          - sonarr
          - radarr
          - lidarr
          - readarr
          - whisparr
          - prowlarr
          - overseerr
        include:
          - app: sonarr
            swagger: https://raw.githubusercontent.com/Sonarr/Sonarr/200396ef7a62af65dd7859006e65037efe302d3f/src/Sonarr.Api.V3/openapi.json
          - app: radarr
            swagger: https://raw.githubusercontent.com/Radarr/Radarr/b08981dee068e1ed23e4f45a0d8fe70ef7bf7703/src/Radarr.Api.V3/openapi.json
          - app: lidarr
            swagger: https://raw.githubusercontent.com/Lidarr/Lidarr/1775dc9fa867cc0def0b67debcf44baa40dd1c50/src/Lidarr.Api.V1/openapi.json
          - app: readarr
            swagger: https://raw.githubusercontent.com/Readarr/Readarr/79ce5abd53d234cd32578ef0bf72d76dd8be2a32/src/Readarr.Api.V1/openapi.json
          - app: whisparr
            # swagger: https://raw.githubusercontent.com/Whisparr/Whisparr/8aef59bcdca16265e0f867fc370b93a5a2b1f9b6/src/Whisparr.Api.V3/openapi.json
            swagger: https://raw.githubusercontent.com/Radarr/Radarr/b08981dee068e1ed23e4f45a0d8fe70ef7bf7703/src/Radarr.Api.V3/openapi.json
          - app: prowlarr
            swagger: https://raw.githubusercontent.com/Prowlarr/Prowlarr/3496263cd2a9065590789dc91988af0ad3e5700e/src/Prowlarr.Api.V1/openapi.json
          - app: overseerr
            swagger: https://raw.githubusercontent.com/sct/overseerr/8251c73ffae678c89eae2de13ee2e9a0afb8d755/overseerr-api.yml

    steps:
      - name: DevOpsArrBOT token
        id: DevOpsArrBOT
        uses: getsentry/action-github-app-token@v2
        with:
          app_id: '305652'
          private_key: ${{ secrets.DEVOPSARRBOT_PRIVATE_KEY }}

      - name: set DevOpsArrBOT config
        run: |
          git config --global user.name "devopsarr[bot]"
          git config --global user.email 127950054+devopsarr[bot]@users.noreply.github.com

      - name: Check out code
        uses: actions/checkout@v4

      - name: Checkout sdk
        uses: actions/checkout@v4
        with:
          repository: devopsarr/${{ matrix.app }}-${{ matrix.lang }}
          path: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
          fetch-depth: 0
          token: ${{ steps.DevOpsArrBOT.outputs.token }}

      # Needed for processing the swaggers
      - name: Set up yq
        uses: frenck/action-setup-yq@v1.0.2
        with:
          version: v4.34.2

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PY_VERSION }}

      - name: Set up Golang
        if: ${{ matrix.lang == 'go' }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Git Version
        run: |
          tag=$(git describe --tags --abbrev=0) &&\
          echo "version=${tag:1}" >> $GITHUB_OUTPUT
        id: version
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: generation
        run: |
          make generate
        env:
          APP: ${{ matrix.app }}
          SDK: ${{ matrix.lang }}
          URL: ${{ matrix.swagger }}
          VERSION: ${{ steps.version.outputs.version }}

      - name: diff
        id: diff
        run: |
          git diff --exit-code ||\
          echo "create-pr=true" >> $GITHUB_OUTPUT
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: create commit
        if: ${{ github.event_name == 'pull_request' && steps.diff.outputs.create-pr == 'true'}}
        run: |
          git checkout -b feature/code-generation &&\
          git add . &&\
          git commit -m "${{ github.event.pull_request.title }}" &&\
          git push --set-upstream origin feature/code-generation -f
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}

      - name: create pull request
        if: ${{ steps.diff.outputs.create-pr == 'true' && github.event_name != 'push' }}
        run: gh pr create -H feature/code-generation -B main --title '${{ github.event.pull_request.title }}' --body 'Code generated' || echo 'PR already created'
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
        env:
          GITHUB_TOKEN: ${{ steps.DevOpsArrBOT.outputs.token }}

      - name: merge pull request
        if: ${{ steps.diff.outputs.create-pr == 'true' && github.event_name == 'push' && github.ref_name == 'main' }}
        run: gh pr merge feature/code-generation --merge
        working-directory: .generated-code/${{ matrix.app }}-${{ matrix.lang }}
        env:
          GITHUB_TOKEN: ${{ steps.DevOpsArrBOT.outputs.token }}